name: Issue Triage
description: Assign label to issues 
resource: repository

configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - if:
          - payloadType: Issues
          - and:
              - isOpen
              - not:
                  and:
                    - isAssignedToSomeone
                    - isLabeled
        then:
          - if:
              - or:
                  - titleContains:
                      pattern: '/(\bc\s*sharp\b|\bc#)/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/(\bc\s*sharp\b|\bc#)/i'
                      isRegex: True
            then:
              - addLabel:
                  label: api:CSharp
          - if:
              - or:
                  - titleContains:
                      pattern: '/\bjava\b/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/\bjava\b/i'
                      isRegex: True
            then:
              - addLabel:
                  label: api:Java
          - if:
              - or:
                  - titleContains:
                      pattern: '/\bjavascript\b/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/\bjavascript\b/i'
                      isRegex: True
            then:
              - addLabel:
                  label: api:JavaScript
          - if:
              - or:
                  - titleContains:
                      pattern: '/\bacl\b/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/\bacl\b/i'
                      isRegex: True
            then:
              - addLabel:
                  label: ep:ACL
