name: Issue Triage
description: Assign label to issues 
resource: repository

configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - if:
          - payloadType: Issues
          - and:
              - isOpen
              - not:
                  and:
                    - isAssignedToSomeone
                    - isLabeled
        then:
          - if:
              - titleContains:
                  pattern: '\bc\s*sharp\b|\bc#'
                  isRegEx: true
            then:
              - addLabel:
                  label: api:CSharp
