name: Issue Triage
description: Assign label to issues 
resource: repository
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - if:
          - payloadType: Issues
          - and:
              - isOpen
              - not:
                  and:
                    - isAssignedToSomeone
                    - isLabeled
        then:
          - if:
              - or:
                  - titleContains:
                      pattern: '/\bcuda\b/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/\bcuda\b/i'
                      isRegex: True
            then:
              - addLabel:
                  label: ep:CUDA
          - if:
              - or:
                  - titleContains:
                      pattern: '/(\bc\s*sharp\b|\bc#)/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/(\bc\s*sharp\b|\bc#)/i'
                      isRegex: True
            then:
              - addLabel:
                  label: api:CSharp
          - if:
              - or:
                  - titleContains:
                      pattern: '/\bjava\b/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/\bjava\b/i'
                      isRegex: True
            then:
              - addLabel:
                  label: api:Java
          - if:
              - or:
                  - titleContains:
                      pattern: '/\bjavascript\b/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/\bjavascript\b/i'
                      isRegex: True
            then:
              - addLabel:
                  label: api:JavaScript
          - if:
              - or:
                  - titleContains:
                      pattern: '/\bacl\b/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/\bacl\b/i'
                      isRegex: True
            then:
              - addLabel:
                  label: ep:ACL
          - if:
              - or:
                  - titleContains:
                      pattern: '/\barmnn\b/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/\barmnn\b/i'
                      isRegex: True
            then:
              - addLabel:
                  label: ep:ArmNN
          - if:
              - or:
                  - titleContains:
                      pattern: '/\bcann\b/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/\bcann\b/i'
                      isRegex: True
            then:
              - addLabel:
                  label: ep:CANN
          - if:
              - or:
                  - titleContains:
                      pattern: '/\bcore-?ml\b/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/\bcore-?ml\b/i'
                      isRegex: True
            then:
              - addLabel:
                  label: ep:CoreML
          - if:
              - or:
                  - titleContains:
                      pattern: '/(\bdirect\s*ml\b|\bdml\b)/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/(\bdirect\s*ml\b|\bdml\b)/i'
                      isRegex: True
            then:
              - addLabel:
                  label: ep:DML
          - if:
              - or:
                  - titleContains:
                      pattern: '/\bmi\s*graph\s*x\b/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/\bmi\s*graph\s*x\b/i'
                      isRegex: True
            then:
              - addLabel:
                  label: ep:MIGraphX
          - if:
              - or:
                  - titleContains:
                      pattern: '/\bone\s*dnn\b/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/\bone\s*dnn\b/i'
                      isRegex: True
            then:
              - addLabel:
                  label: ep:oneDNN
          - if:
              - or:
                  - titleContains:
                      pattern: '/\bopen\s*vino\b/i'
                      isRegex: True
                  - bodyContains:
                      pattern: '/\bopen\s*vino\b/i'
                      isRegex: True
            then:
              - addLabel:
                  label: ep:OpenVINO
