name: Issue Triage
description: Assign label to issues 
resource: repository

configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - if:
          - payloadType: Issues
          - and:
              - isOpen
              - not:
                  and:
                    - isAssignedToSomeone
                    - isLabeled
        then:
          - if:
              - or:
                  - titleContains:
                      pattern: '/(\bc\s*sharp\b|\bc#)/i'
                      isRegEx: true
            then:
              - addLabel:
                  label: api:CSharp
