trigger: none

resources:
  repositories:
  - repository: manylinux
    type: Github
    endpoint: Microsoft
    name: pypa/manylinux
    ref: 5eda9aded5462201e6310105728d33016e637ea7

stages:
- stage: "Python_Packaging_ROCm60_Release"
  jobs:
  - template: templates/rocm.yml
    parameters:
      PythonVersion: '3.8'
      RocmVersion: '6.2'
      RocmVersionPatchSuffix: ""
  - template: templates/rocm.yml
    parameters:
      PythonVersion: '3.9'
      RocmVersion: '6.2'
      RocmVersionPatchSuffix: ""
  - template: templates/rocm.yml
    parameters:
      PythonVersion: '3.10'
      RocmVersion: '6.2'
      RocmVersionPatchSuffix: ""

- stage: "Python_Packaging_ROCm60_Debug"
  jobs:
  - template: templates/rocm.yml
    parameters:
      PythonVersion: '3.8'
      RocmVersion: '6.2'
      RocmVersionPatchSuffix: ""
      BuildConfig: 'Debug'
  - template: templates/rocm.yml
    parameters:
      PythonVersion: '3.9'
      RocmVersion: '6.2'
      RocmVersionPatchSuffix: ""
      BuildConfig: 'Debug'
  - template: templates/rocm.yml
    parameters:
      PythonVersion: '3.10'
      RocmVersion: '6.2'
      RocmVersionPatchSuffix: ""
      BuildConfig: 'Debug'

- stage: "Python_Packaging_ROCm57_Release"
  condition: ne(variables['ORT_DISABLE_PYTHON_PACKAGE_LOCAL_VERSION'], 'true')
  jobs:
  - template: templates/rocm.yml
    parameters:
      PythonVersion: '3.8'
      RocmVersion: '6.1'
  - template: templates/rocm.yml
    parameters:
      PythonVersion: '3.9'
      RocmVersion: '6.1'
  - template: templates/rocm.yml
    parameters:
      PythonVersion: '3.10'
      RocmVersion: '6.1'
