name: Close Stale Issues
description: Close stale issues that have not been updated in 30 days
resource: repository
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
      - frequencies:
          - daily:
              time: 15:00
        filters:
          - hasLabel:
              label: stale
          - isIssue
          - isOpen
          - isNotAssigned
          - noActivitySince:
              days: 30
        actions:
          - addReply:
              reply: "Closing issue due to no activity in 90 days"
          - closeIssue
